use 5.008008;
use ExtUtils::MakeMaker;
# See lib/ExtUtils/MakeMaker.pm for details of how to influence
# the contents of the Makefile that is written.
WriteMakefile(
    NAME              => 'agram',
    VERSION_FROM      => 'agram.pl', # finds $VERSION
    PREREQ_PM         => {}, # e.g., Module::Name => 1.1
    ($] >= 5.005 ?     ## Add these new keywords supported since 5.005
      (ABSTRACT_FROM  => 'agram.pl', # retrieve abstract from module
       AUTHOR         => 'Lincoln Ombelets <Linco@apple.com>') : ()),
);
